version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_n8n
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: n8n
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_n8n
    restart: unless-stopped
    ports:
      - "6379:6379"
